[package]
name = "lrs"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "lrs"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.33", default-features = false, features = ["derive", "nif_version_2_15"] }
suffix = "1.2"
